### ISSUE TITLE
Agree on error details and add TCK tests for that

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/tck#15]
This issue is a bit of a blend between two current missing pieces:

1. It would be great to agree on a common error structure for all parsers. The error structure doesn't have to be JSON but it should be serializable to JSON and contain a minimum of information, formatted in a specific way. For instance, every error should contain a `name`/`id` field, a `reason` field, may contain a field called `path` with a JSON Path string pointing to the place on the document where the error is located, may contain the location of the error as in `lineStart`, `columnStart`, `lineEnd`, and `columnEnd`. These are just proposals for illustration purposes. That's something that needs to be worked out.
2. Once we have the above, include support in the TCK for a way to describe **how** and **why** a test should fail. It is, it's not enough that a test that is supposed to fail, fails. We want to actually check that it failed for the right reason and the error is correctly formatted when serialized as JSON.

What are your thoughts? Would be great to hear from you folks.

**Comment by postatum** [comment]
Hi @fmvilas. I like both ideas.
Am I understanding this right - 1 should be addressed on parsers' side?

**Comment by fmvilas** [comment]
Yeah. 1 is for parsers but I'm starting the discussion here because TCK is the meeting point for both parsers. Happy to move the conversation somewhere else.

**Comment by jonaslagoni** [comment]
I honestly like how JSON Schema defines the tests - https://github.com/json-schema-org/json-schema-test-suite-npm 

This makes it possible to easily use the tests for other things such as #65

**Comment by magicmatatjahu** [comment]
Still relevant.
