### ISSUE TITLE
Is there a test case for security types if they are an empty array if needed

### ISSUE THREAD

**Issue by derberg** [asyncapi/tck#20]
#### Reason/Context
The spec says:
```
If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.
```
I looked for a test case that `has an invalid document with server security of type like userPassword that has not empty array` but couldn't find. Let me know if I'm looking for it wrong, or just confirm it is missing then I will create a PR. I'm doing my first baby steps with TCK so pardon such basic question

**Comment by postatum** [comment]
Hi @derberg.

> I'm doing my first baby steps with TCK so pardon such basic question

Np, you are welcome to ask any questions you have!

Regarding tests:
Do tests in `tests/asyncapi-2.0/Security Requirement Object/invalid-*-non-empty-array.yaml` describe what you mean?

**Comment by derberg** [comment]
@postatum yeap, covered, thanks a bunch, and sorry for bothering. Closing
