### ISSUE TITLE
Test cases observation

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/tck#22]
Hi! observations regarding a few tests cases:

1. Channel bindings that have queue & exchange facet, when these fields are dependant to "is" value so they cannot be both be defined at the same time.
Affects: 
[Reference Object/valid-external-ref-channelBindings.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Reference%20Object/valid-external-ref-channelBindings.yaml)
[Channel Bindings Object/amqp/valid.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Channel%20Bindings%20Object/amqp/valid.yaml)
[Components Object/valid-complete.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Components%20Object/valid-complete.yaml)
Spec: https://github.com/asyncapi/bindings/tree/master/amqp#channel-binding-object

2. Scopes:
* [Security Requirement Object/invalid-oauth2-without-scopes.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Security%20Requirement%20Object/invalid-oauth2-without-scopes.yaml) is expecting to validate without scopes but the API has scopes defined.
* [Security Requirement Object/invalid-openIdConnect-without-scopes.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Security%20Requirement%20Object/invalid-openIdConnect-without-scopes.yaml) The spec does not say that the openIdConnect should have scopes.
Spec: https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#securitySchemeObject

What do you think about these items?
Thanks in advance!

**Comment by postatum** [comment]
Hi @BlockLucas.

I let myself edit your comment to make links "clickable". I hope you don't mind.

On points you're making:
1. I see what you mean - that for example when `is: queue`, facet `exchange` must not be present. But the spec section you refer to doesn't say that `exchange` and `queue` are mutually exclusive. Thus I assumed they both may be present, but only one would be used, depending on the `is` facet value.
2. Both of these documents test [Security Requirement Object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#security-requirement-object) and not [Security Scheme Object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#securitySchemeObject). Former applies security schemes while the latter defines them. And the "Security Requirement Object" section says:
> If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

The line under test in both "Security Requirement Object" yaml docs is:

```yaml
      - mainSecurity: []
```

**Comment by postatum** [comment]
@fmvilas please let us know what do you think on point 1.

**Comment by fmvilas** [comment]
I think it should be valid to have both `queue` and `exchange` independently of the `is` value. It's responsibility of the tooling to use them or not, IMHO.

**Comment by postatum** [comment]
More regarding 2:
Now that I think about it more, the "Security Requirement Object" section doesn't say that the list of scopes "MUST" have some values, so maybe these examples are valid after all.

@fmvilas please comment on this as well.

I refer to [this secrion](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#security-requirement-object). In particular:

> If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

More explanation in my comment above.

**Comment by fmvilas** [comment]
Yeah this one should be valid. Just because there are scopes it doesn't mean you have to use them. Great catch!

**Comment by derberg** [comment]
Are you sure about this one? I was just working on this feature in the asyncapi-parser-js, to always throw error when `oauth` and `openIdConnect` are used but array in server is empty

**Comment by fmvilas** [comment]
It's totally valid. OAuth2 and OpenID Connect are not required to use scopes to work. Scopes are an optional (yet recommended) feature.

**Comment by derberg** [comment]
oh, than this 
```
If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.
```
is slightly confusing and now we have this as a result https://github.com/asyncapi/parser-js/pull/151/files#diff-c3d5db07c30dd8c16e1da041b6f90850R205

**Comment by fmvilas** [comment]
Yes, it's indeed confusing. We should create a follow-up issue to improve this paragraph.

And we should fix the behavior of the parser there. I'm seeing errors validating the streetlights example in the React component.

**Comment by derberg** [comment]
I'll just revert this feature now and make a PR to the spec fine with suggestion on how to make it clearer

**Comment by derberg** [comment]
what do you think https://github.com/asyncapi/asyncapi/pull/426 ?

and the revert PR https://github.com/asyncapi/parser-js/pull/158/files

**Comment by fmvilas** [comment]
Looks great! :+1:

**Comment by derberg** [comment]
@fmvilas all merged

@postatum anything blocking us to merge [this one](https://github.com/asyncapi/tck/pull/28) from your perspective?

**Comment by postatum** [comment]
> @postatum anything blocking us to merge [this one](https://github.com/asyncapi/tck/pull/28) from your perspective?

No. I've just merged it.
