### ISSUE TITLE
Can variable object be really empty or not

### ISSUE THREAD

**Issue by derberg** [asyncapi/tck#30]
#### Reason/Context
This [test](https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Server%20Variable%20Object/valid-empty-object.yaml) case assumes Variable object can be empty as the spec doesn't require any property for [Variable object](https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-servervariableobject-a-server-variable-object) but [JSON Schema](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L212) for the spec has `"minProperties": 1` requirement.

I think we discussed it once but don't forget the conclusion, damn butter. Are we in a position that AsyncAPI JSON Schema complements the AsyncAPI Spec Markdown document or should it just reflect the spec as much as possible, but not complement it. I like the approach that schema complements the spec but I also understand that it might be a bit confusing for the spec audience 🤔 I think I would treat https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L212 as a bug for 2.0.0. What do you think?

**Comment by derberg** [comment]
We have exactly the same situation with https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-oauthflowsobject-a-oauth-flows-object where there is nothing about https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L1285 so in theory this is correct https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Security%20Scheme%20Object/oauth2/valid-empty-flows.yaml#L27

**Comment by derberg** [comment]
@postatum @fmvilas what do you think?

**Comment by postatum** [comment]
Hi. I have no opinion on the issue as I've learned about the `asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json` a moment ago.

**Comment by fmvilas** [comment]
I don't have an opinion either. It doesn't make sense to have it empty or null but not sure it should raise an error.

**Comment by derberg** [comment]
ok then, `.md` file is a spec and the schema is just a `tool` that helps to validate. This way `"minProperties": 1` should be removed because it is not directly stated in the spec, and anyway technically should be allowed cause in nothing is required, minimum should also not be required.

I'll work on a PR to https://github.com/asyncapi/asyncapi/ and https://github.com/asyncapi/asyncapi-node

**Comment by derberg** [comment]
@fmvilas please approve https://github.com/asyncapi/asyncapi-node/pull/14 and https://github.com/asyncapi/asyncapi/pull/424
