### ISSUE TITLE
Invalid security requirement when defining valid test case

### ISSUE THREAD

**Issue by AgustinBettati** [asyncapi/tck#43]
#### Describe the bug
The following test case https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Security%20Scheme%20Object/oauth2/valid-empty-flows.yaml defines an invalid [security requirement object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#security-requirement-object), as it is using scopes which are not defined in the OAuth 2.0 security scheme.

#### Expected behavior
Remove the security requirement definition, to achieve a valid api that defines a OAuth 2.0 security scheme with an empty flows map (original intention of the test case).

**Comment by derberg** [comment]
@AgustinBettati I checked and I don't think that spec requires you to provide only scopes that are defined in the security scheme

**Comment by derberg** [comment]
no followup, looks like this one can stay closed
