### ISSUE TITLE
Clarify invalidity of server variable object example

### ISSUE THREAD

**Issue by derberg** [asyncapi/tck#49]
There is a test case that provides 2 invalid examples of the server variable. One is based on the `example` not matching the `enum` list, which is fine. The other one is based on the `example` not matching `default` -> https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Server%20Variable%20Object/invalid-examples-item.yaml#L24-L29

In my opinion, we can say that the example is not valid if it doesn't match the enum, but if the enum is not provided but just the default value the example must not match the default value.

Once we clarify I can work on a PR to the spec to properly describe (or fix) it because atm it is left for interpretation. 

cc @fmvilas @jonaslagoni

**Comment by derberg** [comment]
to make it clear, I'm asking as we are working now on validating examples only against the enum -> https://github.com/asyncapi/parser-js/issues/100

**Comment by jonaslagoni** [comment]
@derberg I agree with your statement that the examples does not have to match the default value, they are after all just examples and not enums 😄

**Comment by derberg** [comment]
need to find time to work on this 😞

**Comment by magicmatatjahu** [comment]
Still relevant.
