### ISSUE TITLE
Incorrect test case for Schema Object with additional keys

### ISSUE THREAD

**Issue by AgustinBettati** [asyncapi/tck#52]
#### Describe the bug
In the following [test](https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Message%20Bindings%20Object/kafka/Fields%20Types/invalid-key-type.yaml#L20)  a schema object uses an undefined keyword and it is considered invalid.
However when looking at the [schema of Async 2.0](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L354) there is no validation for additional properties in the Schema Object definition, meaning this TCK test should be considered valid.

#### Expected behavior
Modify test providing a invalid value, or consider the test as valid.

**Comment by magicmatatjahu** [comment]
Still relevant.

**Comment by magicmatatjahu** [comment]
Still relevant.

**Comment by derberg** [comment]
@AgustinBettati do you plan to work on it? otherwise I'm not sure it makes sense to keep it open

**Comment by AgustinBettati** [comment]
Hey @derberg! Sorry, I will not be looking into this issue, feel free to adjust as necessary.

**Comment by derberg** [comment]
@AgustinBettati sure, I'll add it to hacktoberfest

The task here is to basically rename `tests/bindings/kafka/0.1.0/Message Bindings Object/invalid-extra-properties.yaml` to `tests/bindings/kafka/0.1.0/Message Bindings Object/valid-extra-properties.yaml`
