### ISSUE TITLE
Integrating TCK as template test

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/tck#65]
#### Reason/Context
This library is the perfect opportunity to develop a wrapper that can be used to test templates. 

#### Description
What do I mean by "test"? The main use-case is to test that the template does not fails to generate valid use-cases of AsyncAPI documents which would increase the overall stability of templates (if they choose to use it of course). 

Questions:
* What are the limits?
* Can we use invalid test cases?
    * I guess that they are primarily for tools and in the template case invalid cases would never reach the template.

Thoughts/ideas?

**Comment by jonaslagoni** [comment]
Related issue - https://github.com/asyncapi/ts-nats-template/issues/11

**Comment by magicmatatjahu** [comment]
Still relevant.

**Comment by magicmatatjahu** [comment]
Still relevant.

**Comment by derberg** [comment]
still valid
