### ISSUE TITLE
initialize all-contributors for this repository

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/tck#84]
#### Reason/Context
Like any other repository in the AsyncAPI organization, we need to initialize all contributors for this repository.

**Comment by magicmatatjahu** [comment]
Still relevant.

**Comment by magicmatatjahu** [comment]
@derberg Could you unstale this and add `good-first-issue` label?

**Comment by derberg** [comment]
but this is not good first issue

**Comment by magicmatatjahu** [comment]
@derberg Why? People can use all-contributors cli to add relevant file and section, I think it's great to be `good-first-issue`. It's not a very hard.
